lr_decay_epoch: 100
exp_lr: False
corrupt_perc: 0
log_nex: False
tblog_interval: 100
data_aug: False
wnoise: False
wnoise_stddev: 1.e-3
pretrained: False
nodropout: False
nobatchnorm: False
lr_decay_rate: 0.1
nesterov: False
log_stats: False
label_smoothing: 0
duplicate: 0,0
g_estim: sgd
epoch_iters: 0
gvar_log_iter: 100
gvar_estim_iter: 10
g_debug: False
gvar_start: 0
g_bsnap_iter: 100
g_osnap_iter: 10
g_optim: False
g_optim_start: 1
no_transform: False
g_epoch: False
g_resume: False
g_batch_size: -1
adam_betas: "(.9,.999)"
adam_eps: 1.e-8
g_mlr: 1
svrg_bsnap_num: -1
niters: 0
